# Generated by Django 5.1.7 on 2025-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/', verbose_name='Kategori Resmi'),
        ),
    ]
