# Generated by Django 5.1.7 on 2025-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('img', 'resim'), ('vid', 'video')], default='img', max_length=5, verbose_name='Medya Türü'),
        ),
    ]
