# Generated by Django 5.1.7 on 2025-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_2',
            field=models.CharField(blank=True, help_text='Cep telefon numaranızı giriniz.', max_length=20, null=True, verbose_name='Cep Telefonu 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_3',
            field=models.CharField(blank=True, help_text='Cep telefon numaranızı giriniz.', max_length=20, null=True, verbose_name='Cep Telefonu 3'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_4',
            field=models.CharField(blank=True, help_text='Cep telefon numaranızı giriniz.', max_length=20, null=True, verbose_name='Cep Telefonu 4'),
        ),
    ]
