# Generated by Django 5.1.7 on 2025-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_mobile_phone_2_contact_mobile_phone_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='instagram_k_adi',
            field=models.CharField(blank=True, help_text='Instagram kullanıcı adınızı giriniz.', max_length=100, null=True, verbose_name='Instagram Kullanıcı Adı'),
        ),
    ]
